name: WODSS-Backend
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - flask
  - flask-swagger-ui
  - requests
  - autopep8
  - ipykernel
  - pandas
  - nbconvert
  - pytest
  - pytest-mock
  - coverage
  - setuptools
  - flasgger
  - flask-cors
  - certifi
  - six
  - setuptools
  - urllib3
